version: '3.8'

services:
  backend:
    image: niritz/truegas
    hostname: truegasdocker
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://db:8000/truegas
    volumes:
      - ./:/app
  db:
    image: mongo
    container_name: database
    ports:
      - "8000:27017"
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
    driver: local
