FROM node:alpine

WORKDIR /app

COPY package*.json ./

RUN npm install -g ts-node

RUN npm install

RUN chgrp -R 0 /app && chmod -R g=u /app

COPY . .

EXPOSE 3000

CMD ["npm", "start"]

HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 CMD curl --fail http://localhost:3001/ || exit 1

# docker-compose up -d