version: '3'
services:
  app:
    image: niritz/truegas
    container_name: truegas-backend-db-server
    hostname: truegasdocker
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://db:8000/truegas

    volumes:
      - ./:/app
  db:
    image: mongo
    ports:
      - "8000:27017"
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
    driver: local
