name: Publish Docker Image to Docker Hub

on:
  push:
     tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag the Docker image
        run: |
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/truegas:${{ github.ref }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/truegas:${{ github.ref }} ${{ secrets.DOCKER_USERNAME }}/truegas:latest

      - name: Push the Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/truegas:${{ github.ref }}
          docker push ${{ secrets.DOCKER_USERNAME }}/truegas:latest