name: Publish Docker Image to Docker Hub

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag the Docker image
        run: |
          docker compose build -t ${{ secrets.DOCKER_USERNAME }}/truegas:${{ github.ref }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/truegas:${{ github.ref }} ${{ secrets.DOCKER_USERNAME }}/truegas:${{ github.ref }}

      - name: Push the Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/truegas:${{ github.ref }}
          docker push ${{ secrets.DOCKER_USERNAME }}/truegas:latest
