name: Publish Docker Compose to Docker Hub

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Install Docker Compose
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get -y install docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker-compose build
          # docker-compose down        
          # docker-compose up -d
          # docker-compose ps

      - name: Create Docker tag and push image
        run: |
          TAG=${{ github.ref }}
          TAG=${TAG#refs/tags/}
          docker tag ${{ secrets.DOCKER_USERNAME }}/truegas ${{ secrets.DOCKER_USERNAME }}/truegas:$TAG
          docker tag ${{ secrets.DOCKER_USERNAME }}/truegas ${{ secrets.DOCKER_USERNAME }}/truegas:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/truegas:$TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/truegas:latest
