name: Publish Docker Compose to Docker Hub

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker compose Build
        run: docker-compose build

      - name: Create Docker tag
        run: |
          TAG=${{ github.ref }}
          TAG=${TAG#refs/tags/}
          docker tag ${{ secrets.DOCKER_USERNAME }}/truegas ${{ secrets.DOCKER_USERNAME }}/truegas:$TAG

      - name: Docker push image
        run: |
          TAG=${{ github.ref }}
          TAG=${TAG#refs/tags/}
          docker push ${{ secrets.DOCKER_USERNAME }}/truegas:$TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/truegas:latest

    services:
      service-name-1:
        image: niritz:truegas
        ports:
          - 3001:3000
# - name: Docker compose up
#   run: |
#     docker-compose down
#     docker-compose up -d

# - name: Check running containers
#   run: docker ps -a
