name: Publish Docker Image to Docker Hub

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/truegas/latest,${{ secrets.DOCKER_USERNAME }}/truegas/${{ github.ref }}
          build-args: |
            DOCKER_TAG=${{ github.ref }}

      - name: Deploy Docker Compose
        run: |
          docker-compose pull
          docker-compose up -d
        working-directory: ./docker-compose
